//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gatelog_a
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateInOut
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<System.DateTime> DateTimeIn { get; set; }
        public Nullable<System.DateTime> DateTimeOut { get; set; }
        public Nullable<int> VehicleTypeId { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ItemsToDeclare ItemsToDeclare { get; set; }
        public virtual PurposeOfVisit PurposeOfVisit { get; set; }
        public virtual User User { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
